name: typetest
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  get_it: ^7.7.0
  kiwi: ^5.0.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  lints: ^4.0.0
  test: ^1.24.0
  kiwi_generator: ^4.2.1
